import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useLocation,Routes,Route,Link} from 'react-router-dom';
import {supabase} from './lib/supabase';
import './styles.css';

function Shell({children,session,profile}){const nav=useNavigate(); const location=useLocation(); const logout=async()=>{await supabase.auth.signOut();nav('/login')};
 const role=profile?.role;
 const links=role==='ADMIN'?[['/admin','Dashboard'],['/admin/passengers','Passengers'],['/admin/drivers','Drivers'],['/admin/vehicles','Vehicles']]:role==='DRIVER'?[['/driver','Dashboard'],['/profile','My Profile']]:[['/passenger','Dashboard'],['/profile','My Profile']];
 return <div className="app"><header><Link className="brand" to={role==='ADMIN'?'/admin':role==='DRIVER'?'/driver':'/passenger'}>Uptown <span>Rides</span></Link><div className="header-user">{profile?.first_name||session?.user?.email}<button onClick={logout}>Logout</button></div></header><div className="layout"><aside>{links.map(([to,label])=><Link className={location.pathname===to?'active':''} key={to} to={to}>{label}</Link>)}</aside><main>{children}</main></div></div>}
function Login({setSession}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const nav=useNavigate(); const submit=async e=>{e.preventDefault();setBusy(true);setError('');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else {setSession(data.session);nav('/');}setBusy(false)};return <Auth title="Welcome back" subtitle="Sign in to Uptown Rides"><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><p className="muted">New passenger or driver? <Link to="/register">Create an account</Link></p></form></Auth>}
function Register(){const [form,setForm]=useState({first_name:'',surname:'',email:'',mobile:'',password:'',role:'PASSENGER'}),[error,setError]=useState(''),[done,setDone]=useState(false),[busy,setBusy]=useState(false);const update=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);setError('');const {data,error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{first_name:form.first_name,surname:form.surname,mobile:form.mobile,requested_role:form.role}}});if(error)setError(error.message);else setDone(true);setBusy(false)};if(done)return <Auth title="Account created" subtitle="Check your email if confirmation is enabled, then sign in."><Link className="primary block" to="/login">Go to sign in</Link></Auth>;return <Auth title="Create your account" subtitle="Join Uptown Rides"><form onSubmit={submit}><div className="grid2"><label>First name<input name="first_name" required value={form.first_name} onChange={update}/></label><label>Surname<input name="surname" required value={form.surname} onChange={update}/></label></div><label>Mobile<input name="mobile" required value={form.mobile} onChange={update}/></label><label>Email<input name="email" type="email" required value={form.email} onChange={update}/></label><label>Account type<select name="role" value={form.role} onChange={update}><option value="PASSENGER">Passenger</option><option value="DRIVER">Driver</option></select></label><label>Password<input name="password" type="password" minLength="8" required value={form.password} onChange={update}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Creating…':'Create account'}</button><p className="muted">Already registered? <Link to="/login">Sign in</Link></p></form></Auth>}
function Auth({title,subtitle,children}){return <div className="auth"><div className="auth-card"><div className="logo-mark">UR</div><h1>{title}</h1><p className="muted">{subtitle}</p>{children}</div></div>}
function Card({title,value,children}){return <div className="card"><p className="muted">{title}</p>{value!==undefined&&<h2>{value}</h2>}{children}</div>}
function Passenger({profile}){return <Shell profile={profile}><h1>Welcome, {profile?.first_name||'Passenger'}</h1><p className="muted">Your Uptown Rides account</p><div className="cards"><Card title="Account status" value={profile?.status||'ACTIVE'}/><Card title="Subscription" value={profile?.subscription_status||'FREE'}/><Card title="Profile" value={profileComplete(profile)+'%'}/></div><section className="panel"><h2>Travel preferences</h2><p>Routes, pickup points, schedules and bookings will be added in Phase 2.</p><Link className="secondary" to="/profile">Complete my profile</Link></section></Shell>}
function Driver({profile}){return <Shell profile={profile}><h1>Driver dashboard</h1><p className="muted">Manage your profile and vehicle information.</p><div className="cards"><Card title="Approval" value={profile?.driver_approval_status||'PENDING'}/><Card title="Availability" value={profile?.driver_availability||'OFFLINE'}/><Card title="Trip status" value={profile?.current_trip_status||'OFF_TRIP'}/></div><section className="panel"><h2>Coming next</h2><p>Trip requests, schedules, navigation, live location and SOS will be introduced in later phases.</p></section></Shell>}
function Admin({profile}){const [stats,setStats]=useState({passengers:0,drivers:0,vehicles:0,active:0,pending:0,available:0});useEffect(()=>{(async()=>{const tables=['passengers','drivers','vehicles'];const counts={};for(const t of tables){const {count}=await supabase.from(t).select('*',{count:'exact',head:true});counts[t]=count||0}const {count:active}=await supabase.from('profiles').select('*',{count:'exact',head:true}).eq('status','ACTIVE');const {count:pending}=await supabase.from('drivers').select('*',{count:'exact',head:true}).eq('approval_status','PENDING');const {count:available}=await supabase.from('vehicles').select('*',{count:'exact',head:true}).eq('status','AVAILABLE');setStats({passengers:counts.passengers,drivers:counts.drivers,vehicles:counts.vehicles,active:active||0,pending:pending||0,available:available||0})})()},[]);return <Shell profile={profile}><h1>Admin dashboard</h1><p className="muted">Uptown Rides operations overview</p><div className="cards"><Card title="Passengers" value={stats.passengers}/><Card title="Drivers" value={stats.drivers}/><Card title="Vehicles" value={stats.vehicles}/><Card title="Active users" value={stats.active}/><Card title="Pending drivers" value={stats.pending}/><Card title="Available vehicles" value={stats.available}/></div></Shell>}
function AdminList({profile,type}){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true);const table=type==='passengers'?'passengers':type==='drivers'?'drivers':'vehicles';useEffect(()=>{(async()=>{const {data}=await supabase.from(table).select('*').order('created_at',{ascending:false});setRows(data||[]);setLoading(false)})()},[table]);return <Shell profile={profile}><div className="page-head"><div><h1>{type[0].toUpperCase()+type.slice(1)}</h1><p className="muted">Manage Uptown Rides {type}.</p></div></div><div className="table-wrap">{loading?<p>Loading…</p>:rows.length===0?<p className="muted">No records yet.</p>:<table><thead><tr>{Object.keys(rows[0]).filter(k=>!['id','user_id'].includes(k)).slice(0,7).map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{Object.entries(r).filter(([k])=>!['id','user_id'].includes(k)).slice(0,7).map(([k,v])=><td key={k}>{String(v??'')}</td>)}</tr>)}</tbody></table>}</div></Shell>}
function Profile({profile}){const [form,setForm]=useState(profile||{}),[msg,setMsg]=useState('');useEffect(()=>setForm(profile||{}),[profile]);if(!profile)return null;const save=async e=>{e.preventDefault();const fields={first_name:form.first_name,surname:form.surname,mobile:form.mobile,email:form.email,gender:form.gender,emergency_contact_name:form.emergency_contact_name,emergency_contact_number:form.emergency_contact_number,home_location:form.home_location,work_location:form.work_location};const {error}=await supabase.from('profiles').update(fields).eq('id',profile.id);setMsg(error?error.message:'Profile saved successfully.');};const u=e=>setForm({...form,[e.target.name]:e.target.value});return <Shell profile={profile}><h1>My profile</h1><form className="panel form" onSubmit={save}><div className="grid2"><label>First name<input name="first_name" value={form.first_name||''} onChange={u}/></label><label>Surname<input name="surname" value={form.surname||''} onChange={u}/></label></div><div className="grid2"><label>Mobile<input name="mobile" value={form.mobile||''} onChange={u}/></label><label>Email<input value={form.email||''} disabled/></label></div><div className="grid2"><label>Gender<input name="gender" value={form.gender||''} onChange={u}/></label><label>Emergency contact name<input name="emergency_contact_name" value={form.emergency_contact_name||''} onChange={u}/></label></div><div className="grid2"><label>Emergency contact number<input name="emergency_contact_number" value={form.emergency_contact_number||''} onChange={u}/></label><label>Home / pickup location<input name="home_location" value={form.home_location||''} onChange={u}/></label></div><label>Work / destination location<input name="work_location" value={form.work_location||''} onChange={u}/></label>{msg&&<p className={msg.includes('success')?'success':'error'}>{msg}</p>}<button className="primary">Save profile</button></form></Shell>}
function profileComplete(p){if(!p)return 0;const fields=['first_name','surname','mobile','email'];return Math.round(fields.filter(x=>p[x]).length/fields.length*100)}
function App(){const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true);const nav=useNavigate();useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(!data.session)setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s){setProfile(null);setLoading(false)}});return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(!session)return;supabase.from('profiles').select('*').eq('id',session.user.id).single().then(({data})=>{setProfile(data);setLoading(false);if(data)nav(data.role==='ADMIN'?'/admin':data.role==='DRIVER'?'/driver':'/passenger')})},[session]);if(loading)return <div className="loading">Loading Uptown Rides…</div>;return <Routes><Route path="/login" element={session?<RedirectByRole profile={profile}/>:<Login setSession={setSession}/>}/><Route path="/register" element={<Register/>}/>{session&&profile?<><Route path="/passenger" element={<Passenger profile={profile}/>}/><Route path="/driver" element={<Driver profile={profile}/>}/><Route path="/admin" element={<Admin profile={profile}/>}/><Route path="/admin/passengers" element={<AdminList profile={profile} type="passengers"/>}/><Route path="/admin/drivers" element={<AdminList profile={profile} type="drivers"/>}/><Route path="/admin/vehicles" element={<AdminList profile={profile} type="vehicles"/>}/><Route path="/profile" element={<Profile profile={profile}/>}/><Route path="*" element={<RedirectByRole profile={profile}/>}/></>:<Route path="*" element={<RedirectByRole profile={null}/>}/>}</Routes>}
function RedirectByRole({profile}){const nav=useNavigate();useEffect(()=>{if(!profile){nav('/login');return}nav(profile.role==='ADMIN'?'/admin':profile.role==='DRIVER'?'/driver':'/passenger')},[profile]);return <div/>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
